# Generated by Django 5.2.15 on 2026-07-04 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('offer_letter', 'Offer Letter'), ('experience_letter', 'Experience Letter'), ('recommendation_letter', 'Recommendation Letter')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Generated/edited letter body text.')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_issued', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_date'],
            },
        ),
    ]
